apiVersion: v1
kind: Service
metadata:
  name: bank-churn-service
spec:
  type: LoadBalancer       
  selector:
    app: bank-churn-app    
  ports:
    - protocol: TCP
      port: 8000           
      targetPort: 8000    